pekko.loglevel = "INFO"
pekko.stdout-loglevel = "INFO"
pekko.actor.default-dispatcher.fork-join-executor.parallelism-min = 4
pekko.actor.default-dispatcher.fork-join-executor.parallelism-factor = 1.0
